# Generated by Django 5.0.3 on 2026-02-08 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('num_identite', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_depense', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_chambre', models.CharField(max_length=10, unique=True)),
                ('type_chambre', models.CharField(choices=[('Simple', 'Simple'), ('Double', 'Double'), ('Suite', 'Suite'), ('Familiale', 'Familiale')], max_length=20)),
                ('prix_nuit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut_actuel', models.CharField(choices=[('Libre', 'Libre'), ('Occupée', 'Occupée'), ('En nettoyage', 'En nettoyage'), ('Hors service', 'Hors service')], default='Libre', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reservation', models.DateTimeField(auto_now_add=True)),
                ('date_arrivee', models.DateField()),
                ('date_depart', models.DateField()),
                ('statut_reser', models.CharField(choices=[('Confirmée', 'Confirmée'), ('En attente', 'En attente'), ('Annulée', 'Annulée'), ('Terminée', 'Terminée')], default='En attente', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='core.client')),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='core.room')),
            ],
            options={
                'ordering': ['-date_reservation'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_paye', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('methode_paiement', models.CharField(choices=[('Espèces', 'Espèces'), ('Carte Bancaire', 'Carte Bancaire'), ('Virement', 'Virement'), ('Mobile Money', 'Mobile Money')], max_length=20)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='core.reservation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_service', models.CharField(max_length=100)),
                ('prix_service', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_service', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.reservation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
