# Generated by Django 5.0.3 on 2026-02-09 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_service', models.CharField(max_length=100, unique=True)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='adresse',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='document_identification',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='nationalite',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='periode_occupation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='expense',
            name='justificatif',
            field=models.FileField(blank=True, null=True, upload_to='justificatifs/'),
        ),
        migrations.AddField(
            model_name='room',
            name='etage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='service',
            name='quantite',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='expense',
            name='categorie',
            field=models.CharField(choices=[('Approvisionnement', 'Approvisionnement'), ('Salaire', 'Salaire'), ('Factures', 'Factures'), ('Maintenance', 'Maintenance')], max_length=100),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='statut_reser',
            field=models.CharField(choices=[('Confirmé', 'Confirmé'), ('Check-in', 'Check-in'), ('Check-out', 'Check-out'), ('Annulé', 'Annulé')], default='Confirmé', max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='statut_actuel',
            field=models.CharField(choices=[('Libre', 'Libre'), ('Occupé', 'Occupé'), ('Sale', 'Sale'), ('Maintenance', 'Maintenance')], default='Libre', max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='type_chambre',
            field=models.CharField(choices=[('Standard', 'Standard'), ('VIP', 'VIP'), ('Suite', 'Suite')], max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='nom_service',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='prix_service',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='service',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lignes', to='core.hotelservice'),
        ),
    ]
