# Generated by Django 5.0.3 on 2026-02-09 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_hotelservice_client_adresse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_etablissement', models.CharField(default='Mon Hôtel', max_length=255)),
                ('adresse', models.TextField(blank=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('nom_gerant', models.CharField(blank=True, max_length=100)),
                ('devise', models.CharField(default='FCFA', max_length=10)),
                ('logo', models.FileField(blank=True, null=True, upload_to='logo/')),
            ],
            options={
                'verbose_name': 'Paramètre',
                'verbose_name_plural': 'Paramètres',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('type_report', models.CharField(max_length=100)),
                ('fichier', models.FileField(upload_to='rapports/')),
            ],
        ),
        migrations.RemoveField(
            model_name='service',
            name='service',
        ),
        migrations.RemoveField(
            model_name='client',
            name='nationalite',
        ),
        migrations.RemoveField(
            model_name='client',
            name='num_identite',
        ),
        migrations.RemoveField(
            model_name='room',
            name='etage',
        ),
        migrations.RemoveField(
            model_name='room',
            name='prix_nuit',
        ),
        migrations.RemoveField(
            model_name='service',
            name='date_service',
        ),
        migrations.RemoveField(
            model_name='service',
            name='prix_unitaire',
        ),
        migrations.RemoveField(
            model_name='service',
            name='quantite',
        ),
        migrations.AddField(
            model_name='payment',
            name='reference_paiement',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='reservation',
            name='montant_avance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='categorie',
            field=models.CharField(choices=[('Toute', 'Toute'), ('Entretien', 'Entretien'), ('Electricite', 'Electricite'), ('Eau', 'Eau'), ('Internet', 'Internet'), ('Maintenance', 'Maintenance')], max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='methode_paiement',
            field=models.CharField(choices=[('Espèces', 'Espèces'), ('Mobile Money', 'Mobile Money'), ('Carte Bancaire', 'Carte Bancaire')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='statut_reser',
            field=models.CharField(choices=[('Toute', 'Toute'), ('Confirmée', 'Confirmée'), ('En cours', 'En cours'), ('Terminée', 'Terminée')], default='Confirmée', max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='statut_actuel',
            field=models.CharField(choices=[('Libre', 'Libre'), ('Occupée', 'Occupée'), ('En maintenance', 'En maintenance'), ('Hors service', 'Hors service')], default='Libre', max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='type_chambre',
            field=models.CharField(choices=[('Simple', 'Simple'), ('Double', 'Double'), ('Suite', 'Suite'), ('Dortoir', 'Dortoir')], max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='nom_service',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='prix_service',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='service',
            name='reservation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.reservation'),
        ),
        migrations.DeleteModel(
            name='HotelService',
        ),
    ]
