# Generated by Django 6.0.2 on 2026-02-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_client_email_hotelsetting_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-date_entree'], 'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-date_paiement'], 'verbose_name': 'Paiement', 'verbose_name_plural': 'Paiements'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-date_reservation'], 'verbose_name': 'Réservation', 'verbose_name_plural': 'Réservations'},
        ),
        migrations.AddField(
            model_name='reservation',
            name='prix_nuit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Prix par nuit (copié depuis la chambre)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='client',
            name='type_document',
            field=models.CharField(choices=[('CNI', "Carte Nationale d'Identité"), ('Passeport', 'Passeport')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='montant_paye',
            field=models.DecimalField(decimal_places=2, help_text='Montant versé par le client', max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference_paiement',
            field=models.CharField(blank=True, help_text='ID transaction Mobile Money ou n° de reçu', max_length=100),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='statut_reser',
            field=models.CharField(choices=[('Confirmée', 'Confirmée'), ('En cours', 'En cours'), ('Terminée', 'Terminée'), ('Annulée', 'Annulée')], default='Confirmée', max_length=20),
        ),
    ]
