# Generated by Django 6.0.2 on 2026-02-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_client_options_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['numero_chambre'], 'verbose_name': 'Chambre', 'verbose_name_plural': 'Chambres'},
        ),
        migrations.AddField(
            model_name='room',
            name='prix_nuit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix par nuit (FCFA)'),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True, help_text='Équipements (Ex: Clim, Wi-Fi, Balcon...)', null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='numero_chambre',
            field=models.CharField(max_length=10, unique=True, verbose_name='N° de Chambre'),
        ),
        migrations.AlterField(
            model_name='room',
            name='type_chambre',
            field=models.CharField(choices=[('Simple', 'Simple'), ('Double', 'Double'), ('Suite', 'Suite'), ('Dortoir', 'Dortoir')], default='Simple', max_length=20),
        ),
    ]
