# Generated by Django 6.0.2 on 2026-02-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_room_options_room_prix_nuit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='justificatif',
            field=models.FileField(blank=True, help_text='Formats acceptés : JPG, PNG, PDF', null=True, upload_to='justificatifs/', verbose_name='Reçu (image ou PDF)'),
        ),
        migrations.AlterField(
            model_name='room',
            name='prix_nuit',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Prix par nuit (FCFA)'),
        ),
    ]
