# Generated by Django 6.0.2 on 2026-03-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_expense_justificatif_alter_room_prix_nuit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='categorie',
            field=models.CharField(choices=[('Toute', 'Toute'), ('Entretien', 'Entretien'), ('Electricite', 'Electricite'), ('Eau', 'Eau'), ('Internet', 'Internet'), ('Maintenance', 'Maintenance'), ('Canal Plus', 'Canal Plus')], max_length=100),
        ),
    ]
