# Generated by Django 6.0.2 on 2026-03-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_hotelsetting_options_client_hotel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='categorie',
            field=models.CharField(max_length=100),
        ),
    ]
