# Generated by Django 6.0.2 on 2026-09-18 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_client_numero_client_date_creation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('heure', models.TimeField(blank=True, null=True, verbose_name='Heure')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='confirmee', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to='core.room', verbose_name='Chambre')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to='core.client', verbose_name='Client')),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to='core.hotelsetting', verbose_name='Hôtel')),
            ],
            options={
                'verbose_name': 'Événement du calendrier',
                'verbose_name_plural': 'Événements du calendrier',
                'ordering': ['date', 'heure', 'id'],
            },
        ),
    ]
