# Generated by Django 6.0.2 on 2026-09-18 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_calendarevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelsetting',
            name='ifu',
            field=models.CharField(blank=True, max_length=50, verbose_name='IFU (Identifiant Fiscal Unique)'),
        ),
        migrations.AddField(
            model_name='hotelsetting',
            name='numero_compte_bancaire',
            field=models.CharField(blank=True, max_length=60, verbose_name='Numéro de compte bancaire'),
        ),
        migrations.AddField(
            model_name='hotelsetting',
            name='rccm',
            field=models.CharField(blank=True, max_length=50, verbose_name='RCCM'),
        ),
    ]
