# Generated by Django 6.0.2 on 2026-09-19 07:55

import django.db.models.deletion
from django.db import migrations, models


def rattacher_services(apps, schema_editor):
    """Services liés à une réservation : hôtel de la chambre.
    Services du catalogue créés avant ce champ (sans réservation) : premier hôtel,
    celui de l'ancienne version mono-hôtel."""
    Service = apps.get_model('core', 'Service')
    HotelSetting = apps.get_model('core', 'HotelSetting')
    for s in Service.objects.filter(reservation__isnull=False).select_related('reservation__chambre'):
        s.hotel_id = s.reservation.chambre.hotel_id
        s.save(update_fields=['hotel'])
    premier = HotelSetting.objects.order_by('pk').first()
    if premier:
        Service.objects.filter(reservation__isnull=True, hotel__isnull=True).update(hotel=premier)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_hotelsetting_fiscal'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.hotelsetting', verbose_name='Hôtel'),
        ),
        migrations.RunPython(rattacher_services, migrations.RunPython.noop),
    ]
